anaconda-community/aggregate

.github/workflows/build.yml
https://anaconda.atlassian.net/browse/CR-45
=> feat: build action

.github/workflows/build.yml
https://anaconda.atlassian.net/browse/CR-66
=> fix: build action inputs

.github/workflows/add-repo.yml, .github/workflows/remove-repo.yml, environment.yml
Adding labels to the PRs created in order to filter for them. Also re-formatting the manifest file so that whitespace is consistent.
Jira: CR-75, CR-76
=> ci(workflows): Add labels to the add/remove pull requests

.github/workflows/add-repo.yml, README.md
When adding a feedstock also add it's dependencies
https://anaconda.atlassian.net/browse/CR-74
=> feat: add deps

.github/workflows/add-repo.yml
find_deps updated to take feedstock instead of package
=> fix: Add repo bug

.github/workflows/pr-build.yml, README.md
https://anaconda.atlassian.net/browse/CR-42
=> feat: Update action to run on PR merge

tools/find_deps.py
https://anaconda.atlassian.net/browse/CR-74
=> fix: adjust build order when we see a dependency later

.github/workflows/pr-build.yml
https://anaconda.atlassian.net/browse/CR-100
=> fix: use correct branch name

environment.yml, manifest.yaml
Add boto3 dep to env and libffi to manifest
=> fix: add boto3 and libffi

.github/workflows/pr-build.yml
https://anaconda.atlassian.net/browse/CR-100
=> fix: branch name main

.github/workflows/add-repo.yml
=> fix: wait for fork

.github/workflows/pr-build.yml
Don't run for merged PRs as we build out top 100
=> chore: disable merged

tools/find_deps.py
=> fix: deps errors

manifest.yaml
Add initial test package to manifest
=> test(manifest): add integration test package to manifest

.github/workflows/update-repo.yml, README.md
https://anaconda.atlassian.net/browse/CR-53
=> chore: update all forks

.github/workflows/remove-repo.yml, README.md, conda_build_config.yaml, conda_build_config_additions.yaml, tools/find_deps.py, tools/find_pinned.py
https://anaconda.atlassian.net/browse/CR-135
=> chore: remove feedstocks for pinned packages

.github/workflows/integration-test.yml
Add integration test flow to modify feedstock recipe
=> test(integration-test): integration test flow

.github/workflows/integration-test.yml
=> test(integration-test): integration test

.github/workflows/integration-test.yml
Provide github token to feedstock checkout
=> fix(integration-test): integration test access

.github/workflows/integration-test.yml
=> fix(integration-test): integration test env

.github/workflows/integration-test.yml
fix syntax for conditional test metric
=> fix(integration-test): fix gha syntax

.github/workflows/integration-test.yml
Use a different github action for test metrics
=> test(integration-test): integration test metrics

.github/workflows/integration-test.yml
Reduce the timeout for checking on build to 10 minutes
=> fix(integration-test): reduce poll period

.github/workflows/update-repo.yml
Update the update feedstocks action to run every 6 hours
=> refactor(update-action): increase update frequency

.github/workflows/integration-test.yml
Simplify reporting to datadog as a single step
=> refactor(integration-test): simplify metric publish

.github/workflows/integration-test.yml
=> fix(integration-test): fix result metric name

.github/workflows/integration-test.yml
Update metric sent to datadog to an event
=> refactor(integration-test): use event rather than metric for dd

.github/workflows/integration-test.yml
Update to new mambda github action
=> refactor(integration-test): upgrade mambda action

.github/workflows/integration-test.yml
update mamba github action commit hash
=> fix(integration-test): mamba gha version

.github/workflows/integration-test.yml, .github/workflows/update-repo.yml
Count the number of feedstocks and send to datadog
=> refactor(update-repo): feedstock count metric

.github/workflows/integration-test.yml
The manual build call param add_deps changed its type
=> fix(integration-test): fix call to manual build

.github/workflows/add-repo.yml, .github/workflows/build-feedstock.yml, .github/workflows/manual-build.yml, environment.yml, tools/crawl_deptree.py, tools/find_deps.py, tools/render.py, tools/sort.py
Switch to crawl dep tree and update recipe render
=> chore: crawl dep tree

tools/crawl_deptree.py
Use feedstock name instead of pkg-feedstock
=> fix: feedstock name

tools/crawl_deptree.py
=> fix: feedstock filter

.github/workflows/sbom-artifact-check.yml
Check repodata.json and the sbom index and check that each repodata package has an associated sbom
=> test(sbom): sbom artifact check

.github/workflows/sbom-artifact-check.yml
Include strategy matrix in order to support checking other architectures
=> refactor(sbom): sbom artifact check

.github/workflows/sbom-artifact-check.yml
remove double quote characters from pacakge name
=> fix(sbom): sbom artifact check

.github/workflows/update-repo.yml, README.md
https://anaconda.atlassian.net/browse/CR-146
=> chore: add new dependencies when updating repos

.github/workflows/update-repo.yml
https://anaconda.atlassian.net/browse/CR-37
=> chore: report errors to datadog

.github/workflows/add-repo.yml, .github/workflows/update-repo.yml
https://anaconda.atlassian.net/browse/CR-36
=> chore: report errors on fork

.github/workflows/add-repo.yml
https://anaconda.atlassian.net/browse/CR-141
=> chore: report feedstock added

.github/workflows/remove-repo.yml
https://anaconda.atlassian.net/browse/CR-142
=> chore: remove event to datadog

.github/workflows/add-repo.yml, .github/workflows/update-repo.yml
https://anaconda.atlassian.net/browse/CR-34
https://anaconda.atlassian.net/browse/CR-35
=> chore: send job metrics to datadog

.github/workflows/update-repo.yml
https://anaconda.atlassian.net/browse/CR-163
=> chore: enable auto merge

.github/workflows/build-feedstock.yml, .github/workflows/manual-build.yml, .github/workflows/pr-build.yml, tools/crawl_deptree.py
https://anaconda.atlassian.net/browse/CR-169
=> chore: add option to only sort dependencies

.github/workflows/sbom-artifact-check.yml
Change sbom check condition to look at the number rather than package names
=> fix(sbom-check): sbom check condition

.github/workflows/sbom-artifact-check.yml
We dont need this anymore, commenting out incase we want to use it later
=> chore: disable sbom name check

.github/workflows/sbom-artifact-check.yml
Update service tags to include module and function
=> refactor(dd_event): service tag update

.github/workflows/add-repo.yml, .github/workflows/integration-test.yml, .github/workflows/remove-repo.yml, .github/workflows/sbom-artifact-check.yml, .github/workflows/update-repo.yml
=> fix(datadog): fix the name of the aggregation_key parameter

.github/workflows/integration-test.yml
pydantic 2 introduced breaking changes.
=> pin pydantic version

environment.yml
pin pydantic for another environmen
=> need to pin pydantic

.github/workflows/sync-pinnings.yml
[AX-276]
[AX-276]: https://anaconda.atlassian.net/browse/AX-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AX-276 - Disable CBC auto updates.

.github/workflows/sync-pinnings-AnacondaRecipes.yml
Decided to include file comparison to not attempt openning a PR if conda_build_config.yaml has not changed.
=> Added a workflow to copy anacondaRecipes conda_build_config.yaml file AX-298
